import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { t3Configured, verifyWithT3 } from './t3n-client.js';

const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT||4173);
const demoProfile={income_tier:'RM5,000–RM7,999',monthly_commitments:2200,safe_spend_limit:1200,identity_status:'verified',source:'T3N selective-disclosure credential (demo)'};
function localAssess(amount){const approved=amount>0&&amount<=demoProfile.safe_spend_limit;return {decision:approved?'APPROVED':'DENIED',amount,safe_spend_limit:demoProfile.safe_spend_limit,reason:approved?`RM${amount.toLocaleString()} is within your verified safe-spend limit.`:`RM${amount.toLocaleString()} exceeds your verified safe-spend limit of RM${demoProfile.safe_spend_limit.toLocaleString()}.`,disclosed:['identity_status','income_tier','safe_spend_limit'],hidden:['full_name','IC_number','bank_account_number','exact_salary','transaction_history'],agent_identity:'T3N agent identity: authenticated (demo mode)',audit_id:`AMG-${Date.now().toString(36).toUpperCase()}`,policy:'spend <= verified safe-spend limit',mode:'demo'};}
async function assess(amount){if(!t3Configured())return localAssess(amount);try{const t3=await verifyWithT3({requested_amount:amount,requested_attributes:['identity_status','income_tier','safe_spend_limit']});const limit=Number(t3.safe_spend_limit??t3.attributes?.safe_spend_limit??0);const approved=Boolean(t3.verified)&&amount<=limit;return {decision:approved?'APPROVED':'DENIED',amount,safe_spend_limit:limit,reason:approved?`RM${amount.toLocaleString()} is within the verified safe-spend limit.`:`RM${amount.toLocaleString()} exceeds the verified safe-spend limit of RM${limit.toLocaleString()}.`,disclosed:['identity_status','income_tier','safe_spend_limit'],hidden:['full_name','IC_number','bank_account_number','exact_salary','transaction_history'],agent_identity:'T3N agent identity: authenticated',audit_id:`AMG-${Date.now().toString(36).toUpperCase()}`,policy:'spend <= verified safe-spend limit',mode:'t3n'};}catch(e){return {...localAssess(amount),agent_identity:'T3N credential unavailable — demo fallback',t3_error:e.message};}}
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body));}
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/api/profile')return json(res,200,{...demoProfile,t3n_configured:t3Configured()});if(req.method==='POST'&&req.url==='/api/assess'){let raw='';for await(const c of req)raw+=c;const a=Number(JSON.parse(raw||'{}').amount);if(!Number.isFinite(a)||a<=0)return json(res,400,{error:'Enter a valid purchase amount.'});return json(res,200,await assess(a));}if(req.method==='GET'){const requested=req.url==='/'?'/index.html':req.url;const safe=path.normalize(requested).replace(/^([.][.][\\/])+/, '');const file=path.join(root,safe);const data=await readFile(file);const type=file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html';res.writeHead(200,{'content-type':`${type}; charset=utf-8`});return res.end(data);}json(res,404,{error:'Not found'});}catch(e){json(res,500,{error:e.message});}});server.listen(port,()=>console.log(`AI Money Guardian running at http://localhost:${port}`));
